# -*- coding: utf-8 -*-
"""RAG_Nutrition_vs_Poetry.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SO-VvuS9zrkJlsimtMO58CYMmJZUhNVq
"""

# Perform Google Colab installs (if running in Google Colab)
import os

if "COLAB_GPU" in os.environ:
    print("[INFO] Running in Google Colab, installing requirements.")
    !pip install PyMuPDF # for reading PDFs with Python
    !pip install tqdm # for progress bars
    !pip install sentence-transformers # for embedding models
    !pip install accelerate # for quantization model loading
    !pip install bitsandbytes # for quantizing models (less storage space)

# Download PDF file
import os
import requests

# Get PDF document
pdf_path = "human-nutrition-text.pdf"

# Download PDF if it doesn't already exist
if not os.path.exists(pdf_path):
  print("File doesn't exist, downloading...")

  # The URL of the PDF you want to download
  url = "https://pressbooks.oer.hawaii.edu/humannutrition2/open/download?type=pdf"

  # The local filename to save the downloaded file
  filename = pdf_path

  # Send a GET request to the URL
  response = requests.get(url)

  # Check if the request was successful
  if response.status_code == 200:
      # Open a file in binary write mode and save the content to it
      with open(filename, "wb") as file:
          file.write(response.content)
      print(f"The file has been downloaded and saved as {filename}")
  else:
      print(f"Failed to download the file. Status code: {response.status_code}")
else:
  print(f"File {pdf_path} exists.")

# Requires !pip install PyMuPDF, see: https://github.com/pymupdf/pymupdf
import fitz # (pymupdf, found this is better than pypdf for our use case, note: licence is AGPL-3.0, keep that in mind if you want to use any code commercially)
from tqdm.auto import tqdm # for progress bars, requires !pip install tqdm

def text_formatter(text: str) -> str:
    """Performs minor formatting on text."""
    cleaned_text = text.replace("\n", " ").strip() # note: this might be different for each doc (best to experiment)

    # Other potential text formatting functions can go here
    return cleaned_text

# Open PDF and get lines/pages
# Note: this only focuses on text, rather than images/figures etc
def open_and_read_pdf(pdf_path: str) -> list[dict]:
    """
    Opens a PDF file, reads its text content page by page, and collects statistics.

    Parameters:
        pdf_path (str): The file path to the PDF document to be opened and read.

    Returns:
        list[dict]: A list of dictionaries, each containing the page number
        (adjusted), character count, word count, sentence count, token count, and the extracted text
        for each page.
    """
    doc = fitz.open(pdf_path)  # open a document
    pages_and_texts = []
    for page_number, page in tqdm(enumerate(doc)):  # iterate the document pages
        text = page.get_text()  # get plain text encoded as UTF-8
        text = text_formatter(text)
        pages_and_texts.append({"page_number": page_number - 41,  # adjust page numbers since our PDF starts on page 42
                                "page_char_count": len(text),
                                "page_word_count": len(text.split(" ")),
                                "page_sentence_count_raw": len(text.split(". ")),
                                "page_token_count": len(text) / 4,  # 1 token = ~4 chars, see: https://help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them
                                "text": text})
    return pages_and_texts

pages_and_texts = open_and_read_pdf(pdf_path=pdf_path)
pages_and_texts[:2]

pages_and_texts[50]

import pandas as pd

df = pd.DataFrame(pages_and_texts)
df.head()

import random

random.sample(pages_and_texts, k=3)

import pandas as pd

df = pd.DataFrame(pages_and_texts)
df.head()

# Get stats
df.describe().round(2)

from spacy.lang.en import English # see https://spacy.io/usage for install instructions

nlp = English()

# Add a sentencizer pipeline, see https://spacy.io/api/sentencizer/
nlp.add_pipe("sentencizer")

# Create a document instance as an example
doc = nlp("This is a sentence. This another sentence.")
assert len(list(doc.sents)) == 2

# Access the sentences of the document
list(doc.sents)

for item in tqdm(pages_and_texts):
    item["sentences"] = list(nlp(item["text"]).sents)

    # Make sure all sentences are strings
    item["sentences"] = [str(sentence) for sentence in item["sentences"]]

    # Count the sentences
    item["page_sentence_count_spacy"] = len(item["sentences"])

# Inspect an example
import random
random.sample(pages_and_texts, k=1)

df = pd.DataFrame(pages_and_texts)
df.describe().round(2)

# Define split size to turn groups of sentences into chunks
num_sentence_chunk_size = 10

# Create a function that recursively splits a list into desired sizes
def split_list(input_list: list,
               slice_size: int) -> list[list[str]]:
    """
    Splits the input_list into sublists of size slice_size (or as close as possible).

    For example, a list of 17 sentences would be split into two lists of [[10], [7]]
    """
    return [input_list[i:i + slice_size] for i in range(0, len(input_list), slice_size)]

# Loop through pages and texts and split sentences into chunks
for item in tqdm(pages_and_texts):
    item["sentence_chunks"] = split_list(input_list=item["sentences"],
                                         slice_size=num_sentence_chunk_size)
    item["num_chunks"] = len(item["sentence_chunks"])

# Sample an example from the group (note: many samples have only 1 chunk as they have <=10 sentences total)
random.sample(pages_and_texts, k=1)

# Create a DataFrame to get stats
df = pd.DataFrame(pages_and_texts)
df.describe().round(2)

import re

# Split each chunk into its own item
pages_and_chunks = []
for item in tqdm(pages_and_texts):
    for sentence_chunk in item["sentence_chunks"]:
        chunk_dict = {}
        chunk_dict["page_number"] = item["page_number"]

        # Join the sentences together into a paragraph-like structure, aka a chunk (so they are a single string)
        joined_sentence_chunk = "".join(sentence_chunk).replace("  ", " ").strip()
        joined_sentence_chunk = re.sub(r'\.([A-Z])', r'. \1', joined_sentence_chunk) # ".A" -> ". A" for any full-stop/capital letter combo
        chunk_dict["sentence_chunk"] = joined_sentence_chunk

        # Get stats about the chunk
        chunk_dict["chunk_char_count"] = len(joined_sentence_chunk)
        chunk_dict["chunk_word_count"] = len([word for word in joined_sentence_chunk.split(" ")])
        chunk_dict["chunk_token_count"] = len(joined_sentence_chunk) / 4 # 1 token = ~4 characters

        pages_and_chunks.append(chunk_dict)

# How many chunks do we have?
len(pages_and_chunks)

# View a random sample
random.sample(pages_and_chunks, k=1)

# Get stats about our chunks
df = pd.DataFrame(pages_and_chunks)
df.describe().round(2)

# Show random chunks with under 30 tokens in length
min_token_length = 30
for row in df[df["chunk_token_count"] <= min_token_length].sample(5).iterrows():
    print(f'Chunk token count: {row[1]["chunk_token_count"]} | Text: {row[1]["sentence_chunk"]}')

pages_and_chunks_over_min_token_len = df[df["chunk_token_count"] > min_token_length].to_dict(orient="records")
pages_and_chunks_over_min_token_len[:2]

# Requires !pip install sentence-transformers
from sentence_transformers import SentenceTransformer
embedding_model = SentenceTransformer(model_name_or_path="all-mpnet-base-v2",
                                      device="cpu") # choose the device to load the model to (note: GPU will often be *much* faster than CPU)

# Create a list of sentences to turn into numbers
sentences = [
    "The Sentences Transformers library provides an easy and open-source way to create embeddings.",
    "Sentences can be embedded one by one or as a list of strings.",
    "Embeddings are one of the most powerful concepts in machine learning!",
    "Learn to use embeddings well and you'll be well on your way to being an AI engineer."
]

# Sentences are encoded/embedded by calling model.encode()
embeddings = embedding_model.encode(sentences)
embeddings_dict = dict(zip(sentences, embeddings))

# See the embeddings
for sentence, embedding in embeddings_dict.items():
    print("Sentence:", sentence)
    print("Embedding:", embedding)
    print("")

single_sentence = "Yo! How cool are embeddings?"
single_embedding = embedding_model.encode(single_sentence)
print(f"Sentence: {single_sentence}")
print(f"Embedding:\n{single_embedding}")
print(f"Embedding size: {single_embedding.shape}")

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# # Uncomment to see how long it takes to create embeddings on CPU
# # # Make sure the model is on the CPU
# # embedding_model.to("cpu")
# 
# # # Embed each chunk one by one
# # for item in tqdm(pages_and_chunks_over_min_token_len):
# #     item["embedding"] = embedding_model.encode(item["sentence_chunk"])

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# # Send the model to the GPU
# embedding_model.to("cuda") # requires a GPU installed, for reference on my local machine, I'm using a NVIDIA RTX 4090
# 
# # Create embeddings one by one on the GPU
# for item in tqdm(pages_and_chunks_over_min_token_len):
#     item["embedding"] = embedding_model.encode(item["sentence_chunk"])

# Turn text chunks into a single list
text_chunks = [item["sentence_chunk"] for item in pages_and_chunks_over_min_token_len]

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# # Embed all texts in batches
# text_chunk_embeddings = embedding_model.encode(text_chunks,
#                                                batch_size=32, # you can use different batch sizes here for speed/performance, I found 32 works well for this use case
#                                                convert_to_tensor=True) # optional to return embeddings as tensor instead of array
# 
# text_chunk_embeddings

# Save embeddings to file
text_chunks_and_embeddings_df = pd.DataFrame(pages_and_chunks_over_min_token_len)
embeddings_df_save_path = "text_chunks_and_embeddings_df.csv"
text_chunks_and_embeddings_df.to_csv(embeddings_df_save_path, index=False)

# Import saved file and view
text_chunks_and_embedding_df_load = pd.read_csv(embeddings_df_save_path)
text_chunks_and_embedding_df_load.head()

import random

import torch
import numpy as np
import pandas as pd

device = "cuda" if torch.cuda.is_available() else "cpu"

# Import texts and embedding df
text_chunks_and_embedding_df = pd.read_csv("text_chunks_and_embeddings_df.csv")

# Convert embedding column back to np.array (it got converted to string when it got saved to CSV)
text_chunks_and_embedding_df["embedding"] = text_chunks_and_embedding_df["embedding"].apply(lambda x: np.fromstring(x.strip("[]"), sep=" "))

# Convert texts and embedding df to list of dicts
pages_and_chunks = text_chunks_and_embedding_df.to_dict(orient="records")

# Convert embeddings to torch tensor and send to device (note: NumPy arrays are float64, torch tensors are float32 by default)
embeddings = torch.tensor(np.array(text_chunks_and_embedding_df["embedding"].tolist()), dtype=torch.float32).to(device)
embeddings.shape

text_chunks_and_embedding_df.head()

embeddings[0]

from sentence_transformers import util, SentenceTransformer

embedding_model = SentenceTransformer(model_name_or_path="all-mpnet-base-v2",
                                      device=device) # choose the device to load the model to

# 1. Define the query
# Note: This could be anything. But since we're working with a nutrition textbook, we'll stick with nutrition-based queries.
query = "macronutrients functions"
print(f"Query: {query}")

# 2. Embed the query to the same numerical space as the text examples
# Note: It's important to embed your query with the same model you embedded your examples with.
query_embedding = embedding_model.encode(query, convert_to_tensor=True)

# 3. Get similarity scores with the dot product (we'll time this for fun)
from time import perf_counter as timer

start_time = timer()
dot_scores = util.dot_score(a=query_embedding, b=embeddings)[0]
end_time = timer()

print(f"Time take to get scores on {len(embeddings)} embeddings: {end_time-start_time:.5f} seconds.")

# 4. Get the top-k results (we'll keep this to 5)
top_results_dot_product = torch.topk(dot_scores, k=5)
top_results_dot_product

larger_embeddings = torch.randn(100*embeddings.shape[0], 768).to(device)
print(f"Embeddings shape: {larger_embeddings.shape}")

# Perform dot product across 168,000 embeddings
start_time = timer()
dot_scores = util.dot_score(a=query_embedding, b=larger_embeddings)[0]
end_time = timer()

print(f"Time take to get scores on {len(larger_embeddings)} embeddings: {end_time-start_time:.5f} seconds.")

# Define helper function to print wrapped text
import textwrap

def print_wrapped(text, wrap_length=80):
    wrapped_text = textwrap.fill(text, wrap_length)
    print(wrapped_text)

print(f"Query: '{query}'\n")
print("Results:")
# Loop through zipped together scores and indicies from torch.topk
for score, idx in zip(top_results_dot_product[0], top_results_dot_product[1]):
    print(f"Score: {score:.4f}")
    # Print relevant sentence chunk (since the scores are in descending order, the most relevant chunk will be first)
    print("Text:")
    print_wrapped(pages_and_chunks[idx]["sentence_chunk"])
    # Print the page number too so we can reference the textbook further (and check the results)
    print(f"Page number: {pages_and_chunks[idx]['page_number']}")
    print("\n")

def retrieve_relevant_resources(query, embeddings, model=embedding_model, n_resources_to_return=5):
    """
    Takes a query, embeds it, compares it with document embeddings,
    and returns the top-k most relevant chunks.
    """
    query_embedding = model.encode(query, convert_to_tensor=True)
    query_embedding = query_embedding.to(embeddings.device)

    dot_scores = util.dot_score(query_embedding, embeddings)[0]

    scores, indices = torch.topk(dot_scores, k=n_resources_to_return)

    return scores, indices


def print_top_results_and_scores(query, embeddings, pages_and_chunks, n_resources_to_return=5):
    """
    Prints top-k retrieved chunks with their similarity scores.
    """
    scores, indices = retrieve_relevant_resources(
        query=query,
        embeddings=embeddings,
        n_resources_to_return=n_resources_to_return
    )

    print(f"Query: {query}\n")
    print("Top retrieved chunks:\n")

    for score, idx in zip(scores, indices):
        idx = idx.item()
        print(f"Score: {score:.4f}")
        print("Text:")
        print_wrapped(pages_and_chunks[idx]["sentence_chunk"])
        print(f"Page number: {pages_and_chunks[idx]['page_number']}")
        print("-" * 80)

query = "symptoms of pellagra"

print_top_results_and_scores(
    query=query,
    embeddings=embeddings,
    pages_and_chunks=pages_and_chunks,
    n_resources_to_return=5
)

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

model_id = "Qwen/Qwen2.5-1.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_id)

llm_model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    device_map="auto"
)

print("LLM loaded successfully.")

def generate_llm_answer(input_text, max_new_tokens=256):
    messages = [
        {"role": "user", "content": input_text}
    ]

    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    model_device = next(llm_model.parameters()).device

    inputs = tokenizer(prompt, return_tensors="pt").to(model_device)

    outputs = llm_model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False,
        pad_token_id=tokenizer.eos_token_id
    )

    # Only decode newly generated tokens, not the original prompt
    generated_tokens = outputs[0][inputs["input_ids"].shape[-1]:]
    answer = tokenizer.decode(generated_tokens, skip_special_tokens=True)

    return answer


test_question = "What are macronutrients?"
answer = generate_llm_answer(test_question)

print("Question:", test_question)
print("Answer:")
print(answer)

def prompt_formatter(query, context_items):
    """
    Formats retrieved PDF chunks into a prompt for the LLM.
    """

    context = "\n\n".join(
        [
            f"Context {i+1} | Page {item['page_number']} | Score {item['score']:.4f}\n"
            f"{item['sentence_chunk']}"
            for i, item in enumerate(context_items)
        ]
    )

    prompt = f"""
You are a helpful assistant answering questions based on a PDF document.

Use only the context below to answer the question.
Do not use outside knowledge.
If the answer is not available in the context, say:
"The document does not provide enough information."

Context:
{context}

Question:
{query}

Answer:
"""

    messages = [
        {"role": "user", "content": prompt}
    ]

    formatted_prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    return formatted_prompt

def ask(query, n_resources_to_return=2, max_new_tokens=256):
    """
    Full RAG pipeline:
    1. Retrieve relevant chunks from PDF
    2. Add retrieved chunks to the prompt as context
    3. Generate an answer using the LLM
    """

    # 1. Retrieve relevant chunks
    scores, indices = retrieve_relevant_resources(
        query=query,
        embeddings=embeddings,
        n_resources_to_return=n_resources_to_return
    )

    # 2. Prepare context items
    context_items = []

    for score, idx in zip(scores, indices):
        idx = idx.item()
        item = pages_and_chunks[idx].copy()
        item["score"] = score.item()
        context_items.append(item)

    # 3. Format prompt with retrieved context
    prompt = prompt_formatter(
        query=query,
        context_items=context_items
    )

    # 4. Tokenize prompt
    model_device = next(llm_model.parameters()).device
    inputs = tokenizer(prompt, return_tensors="pt").to(model_device)

    # 5. Generate answer
    outputs = llm_model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False,
        pad_token_id=tokenizer.eos_token_id
    )

    # 6. Decode only newly generated tokens
    generated_tokens = outputs[0][inputs["input_ids"].shape[-1]:]
    answer = tokenizer.decode(generated_tokens, skip_special_tokens=True)

    return answer, context_items

query = "What are the symptoms of pellagra?"

answer, context_items = ask(
    query=query,
    n_resources_to_return=2,
    max_new_tokens=256
)

print("Query:")
print(query)

print("\nRAG Answer:")
print(answer)

print("\nRetrieved Contexts:")
for item in context_items:
    print(f"Score: {item['score']:.4f}")
    print(f"Page number: {item['page_number']}")
    print_wrapped(item["sentence_chunk"])
    print("-" * 80)

query = "What are macronutrients, and what roles do they play in the human body?"

answer, context_items = ask(
    query=query,
    n_resources_to_return=2,
    max_new_tokens=256
)

print("Query:")
print(query)

print("\nRAG Answer:")
print(answer)

print("\nRetrieved Contexts:")
for item in context_items:
    print(f"Score: {item['score']:.4f}")
    print(f"Page number: {item['page_number']}")
    print_wrapped(item["sentence_chunk"])
    print("-" * 80)

import pandas as pd

evaluation_queries = [
    "What are the symptoms of pellagra?",
    "What are macronutrients, and what roles do they play in the human body?",
    "How does water help the human body?",
    "What is the difference between macronutrients and micronutrients?",
    "What are water-soluble vitamins?"
]

rag_results = []

for query in evaluation_queries:
    answer, context_items = ask(
        query=query,
        n_resources_to_return=2,
        max_new_tokens=256
    )

    retrieved_pages = [item["page_number"] for item in context_items]
    retrieval_scores = [round(item["score"], 4) for item in context_items]

    rag_results.append({
        "Query": query,
        "RAG Answer": answer,
        "Retrieved Pages": retrieved_pages,
        "Retrieval Scores": retrieval_scores
    })

rag_results_df = pd.DataFrame(rag_results)
rag_results_df

nutrition_dataset = {
    "name": "Human Nutrition PDF",
    "pdf_path": "human-nutrition-text.pdf",
    "chunks": pages_and_chunks,
    "embeddings": embeddings
}

print(nutrition_dataset["name"])
print("Number of chunks:", len(nutrition_dataset["chunks"]))
print("Embedding shape:", nutrition_dataset["embeddings"].shape)

import os
import requests

poetry_pdf_path = "leaves_of_grass.pdf"
poetry_url = "https://www.waltwhitman.com/leaves-of-grass.pdf"

if not os.path.exists(poetry_pdf_path):
    headers = {"User-Agent": "Mozilla/5.0"}
    response = requests.get(poetry_url, headers=headers)

    if response.status_code == 200:
        with open(poetry_pdf_path, "wb") as f:
            f.write(response.content)
        print("Poetry PDF downloaded successfully.")
    else:
        print("Failed to download PDF.")
        print("Status code:", response.status_code)
else:
    print("Poetry PDF already exists.")

import fitz

doc = fitz.open(poetry_pdf_path)

print("Number of pages:", len(doc))

sample_page = doc.load_page(5)
sample_text = sample_page.get_text("text")

doc.close()

print(sample_text[:1500])

import fitz

doc = fitz.open(poetry_pdf_path)

for page_num in [5, 10, 15, 20, 25, 30, 35, 40, 50]:
    page = doc.load_page(page_num)
    text = page.get_text("text")
    print("=" * 100)
    print("PAGE:", page_num)
    print(text[:1000])

doc.close()

import fitz

search_terms = [
    "ONE'S-SELF I SING",
    "I celebrate myself",
    "Song of Myself",
    "BOOK I. INSCRIPTIONS"
]

doc = fitz.open(poetry_pdf_path)

for page_num in range(len(doc)):
    text = doc.load_page(page_num).get_text("text")
    lower_text = text.lower()

    if any(term.lower() in lower_text for term in search_terms):
        print("=" * 100)
        print("Possible poetry start page:", page_num)
        print(text[:1200])
        break

doc.close()

import fitz
import re
import pandas as pd
from tqdm.auto import tqdm

def clean_poetry_text(text: str) -> str:
    """
    Cleans poetry text while preserving line breaks.
    """
    text = text.replace("\xa0", " ")
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def should_skip_poetry_line(line: str) -> bool:
    """
    Removes table-of-contents lines, page numbers, URLs, and decorative lines.
    """
    line = line.strip()

    if line == "":
        return True

    if re.fullmatch(r"\d+", line):
        return True

    if len(line) <= 2:
        return True

    if "Free eBooks" in line or "WaltWhitman.com" in line:
        return True

    # Table of contents style lines: TITLE .......... 221
    if re.search(r"\.{5,}\s*\d+$", line):
        return True

    return False


def open_and_read_poetry_pdf(pdf_path: str, start_page: int = 0, end_page: int | None = None) -> list[dict]:
    """
    Reads a poetry PDF while preserving line structure.
    """
    doc = fitz.open(pdf_path)

    if end_page is None:
        end_page = len(doc)

    pages_and_texts = []

    for page_number in tqdm(range(start_page, end_page)):
        page = doc.load_page(page_number)
        text = page.get_text("text")
        text = clean_poetry_text(text)

        pages_and_texts.append({
            "page_number": page_number,
            "page_char_count": len(text),
            "page_word_count": len(text.split()),
            "page_token_count": len(text) / 4,
            "text": text
        })

    doc.close()
    return pages_and_texts


def build_poetry_rag_dataset_from_pdf(
    pdf_path: str,
    dataset_name: str,
    embedding_model,
    device,
    start_page: int = 0,
    end_page: int | None = None,
    lines_per_chunk: int = 10,
    min_token_length: int = 8
):
    """
    Builds a RAG dataset from a poetry PDF using line-based chunking.
    """

    pages_and_texts = open_and_read_poetry_pdf(
        pdf_path=pdf_path,
        start_page=start_page,
        end_page=end_page
    )

    poetry_chunks = []

    for page in tqdm(pages_and_texts):
        raw_lines = page["text"].split("\n")

        lines = []

        for line in raw_lines:
            line = line.strip()

            if should_skip_poetry_line(line):
                continue

            lines.append(line)

        for i in range(0, len(lines), lines_per_chunk):
            chunk_lines = lines[i:i + lines_per_chunk]
            chunk_text = "\n".join(chunk_lines).strip()

            if len(chunk_text) == 0:
                continue

            chunk_dict = {
                "page_number": page["page_number"],
                "sentence_chunk": chunk_text,
                "chunk_char_count": len(chunk_text),
                "chunk_word_count": len(chunk_text.split()),
                "chunk_token_count": len(chunk_text) / 4,
                "document_type": "poetry"
            }

            poetry_chunks.append(chunk_dict)

    df_poetry_chunks = pd.DataFrame(poetry_chunks)

    poetry_chunks_over_min_token_len = df_poetry_chunks[
        df_poetry_chunks["chunk_token_count"] > min_token_length
    ].to_dict(orient="records")

    text_chunks = [
        item["sentence_chunk"]
        for item in poetry_chunks_over_min_token_len
    ]

    poetry_embeddings = embedding_model.encode(
        text_chunks,
        batch_size=32,
        convert_to_tensor=True
    ).to(device)

    poetry_dataset = {
        "name": dataset_name,
        "pdf_path": pdf_path,
        "chunks": poetry_chunks_over_min_token_len,
        "embeddings": poetry_embeddings,
        "document_type": "poetry"
    }

    print(f"Dataset name: {dataset_name}")
    print(f"Document type: poetry")
    print(f"Start page: {start_page}")
    print(f"Number of chunks: {len(poetry_dataset['chunks'])}")
    print(f"Embedding shape: {poetry_dataset['embeddings'].shape}")

    return poetry_dataset

poetry_dataset = build_poetry_rag_dataset_from_pdf(
    pdf_path=poetry_pdf_path,
    dataset_name="Leaves of Grass Poetry PDF",
    embedding_model=embedding_model,
    device=device,
    start_page=11,
    lines_per_chunk=10,
    min_token_length=8
)

len(poetry_dataset["chunks"])

import random

for item in random.sample(poetry_dataset["chunks"], k=5):
    print("Page:", item["page_number"])
    print("Token count:", round(item["chunk_token_count"], 2))
    print(item["sentence_chunk"])
    print("-" * 100)

bad_terms = ["Free eBooks", "WaltWhitman.com", "Contents"]

bad_chunks = [
    item for item in poetry_dataset["chunks"]
    if any(term.lower() in item["sentence_chunk"].lower() for term in bad_terms)
]

print("Number of suspicious chunks:", len(bad_chunks))

for item in bad_chunks[:5]:
    print("Page:", item["page_number"])
    print(item["sentence_chunk"])
    print("-" * 80)

poetry_df = pd.DataFrame(poetry_dataset["chunks"])

poetry_df[[
    "chunk_char_count",
    "chunk_word_count",
    "chunk_token_count"
]].describe().round(2)

poetry_query = "Which lines mention death or mortality?"

print_top_results_and_scores(
    query=poetry_query,
    embeddings=poetry_dataset["embeddings"],
    pages_and_chunks=poetry_dataset["chunks"],
    n_resources_to_return=3
)

poetry_query = "Which lines express loneliness or sadness?"

print_top_results_and_scores(
    query=poetry_query,
    embeddings=poetry_dataset["embeddings"],
    pages_and_chunks=poetry_dataset["chunks"],
    n_resources_to_return=3
)

poetry_query = "Which lines connect love, democracy, and religion?"

print_top_results_and_scores(
    query=poetry_query,
    embeddings=poetry_dataset["embeddings"],
    pages_and_chunks=poetry_dataset["chunks"],
    n_resources_to_return=3
)

def prompt_formatter_poetry(query, context_items):
    """
    Formats retrieved poetry excerpts into a literary RAG prompt.
    """

    context = "\n\n".join(
        [
            f"Excerpt {i+1} | Page {item['page_number']} | Score {item['score']:.4f}\n"
            f"{item['sentence_chunk']}"
            for i, item in enumerate(context_items)
        ]
    )

    prompt = f"""
You are a careful literary assistant answering questions based on retrieved excerpts from a poetry PDF.

Use only the excerpts below.
If you interpret a theme, emotion, or symbol, clearly say that it is an interpretation based on the retrieved lines.
Do not claim the poet's exact intention unless it is directly stated.
Do not use outside knowledge about the poet or the book.
If the excerpts are not enough to answer, say:
"The document does not provide enough information."

Retrieved poetry excerpts:
{context}

Question:
{query}

Answer:
"""

    messages = [
        {"role": "user", "content": prompt}
    ]

    formatted_prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    return formatted_prompt

def ask_poetry(query, dataset, n_resources_to_return=3, max_new_tokens=256):
    """
    Full RAG pipeline for poetry:
    1. Retrieve relevant poetry excerpts
    2. Add retrieved excerpts to a literary prompt
    3. Generate an answer using the LLM
    """

    scores, indices = retrieve_relevant_resources(
        query=query,
        embeddings=dataset["embeddings"],
        n_resources_to_return=n_resources_to_return
    )

    context_items = []

    for score, idx in zip(scores, indices):
        idx = idx.item()
        item = dataset["chunks"][idx].copy()
        item["score"] = score.item()
        context_items.append(item)

    prompt = prompt_formatter_poetry(
        query=query,
        context_items=context_items
    )

    model_device = next(llm_model.parameters()).device
    inputs = tokenizer(prompt, return_tensors="pt").to(model_device)

    outputs = llm_model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False,
        pad_token_id=tokenizer.eos_token_id
    )

    generated_tokens = outputs[0][inputs["input_ids"].shape[-1]:]
    answer = tokenizer.decode(generated_tokens, skip_special_tokens=True)

    return answer, context_items

query = "Which lines mention death or mortality?"

answer, context_items = ask_poetry(
    query=query,
    dataset=poetry_dataset,
    n_resources_to_return=3,
    max_new_tokens=256
)

print("Query:")
print(query)

print("\nPoetry RAG Answer:")
print(answer)

print("\nRetrieved Poetry Excerpts:")
for item in context_items:
    print(f"Score: {item['score']:.4f}")
    print(f"Page number: {item['page_number']}")
    print(item["sentence_chunk"])
    print("-" * 100)

query = "Which lines express loneliness or sadness?"

answer, context_items = ask_poetry(
    query=query,
    dataset=poetry_dataset,
    n_resources_to_return=3,
    max_new_tokens=256
)

print("Query:")
print(query)

print("\nPoetry RAG Answer:")
print(answer)

print("\nRetrieved Poetry Excerpts:")
for item in context_items:
    print(f"Score: {item['score']:.4f}")
    print(f"Page number: {item['page_number']}")
    print(item["sentence_chunk"])
    print("-" * 100)

def ask_from_dataset(query, dataset, n_resources_to_return=2, max_new_tokens=256):
    """
    Generic factual RAG pipeline for a selected dataset.
    This will be used for the Human Nutrition PDF.
    """

    scores, indices = retrieve_relevant_resources(
        query=query,
        embeddings=dataset["embeddings"],
        n_resources_to_return=n_resources_to_return
    )

    context_items = []

    for score, idx in zip(scores, indices):
        idx = idx.item()
        item = dataset["chunks"][idx].copy()
        item["score"] = score.item()
        context_items.append(item)

    prompt = prompt_formatter(
        query=query,
        context_items=context_items
    )

    model_device = next(llm_model.parameters()).device
    inputs = tokenizer(prompt, return_tensors="pt").to(model_device)

    outputs = llm_model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False,
        pad_token_id=tokenizer.eos_token_id
    )

    generated_tokens = outputs[0][inputs["input_ids"].shape[-1]:]
    answer = tokenizer.decode(generated_tokens, skip_special_tokens=True)

    return answer, context_items

import pandas as pd

comparison_rows = []

# Factual textbook queries
nutrition_tests = [
    "What are the symptoms of pellagra?",
    "What are macronutrients, and what roles do they play in the human body?",
    "What is the difference between macronutrients and micronutrients?"
]

for query in nutrition_tests:
    answer, context_items = ask_from_dataset(
        query=query,
        dataset=nutrition_dataset,
        n_resources_to_return=2,
        max_new_tokens=256
    )

    comparison_rows.append({
        "Dataset": nutrition_dataset["name"],
        "Document Type": "Factual textbook",
        "Chunking Strategy": "Sentence-based chunking",
        "Query Type": "Factual question",
        "Query": query,
        "Chunk Count": len(nutrition_dataset["chunks"]),
        "Embedding Shape": str(tuple(nutrition_dataset["embeddings"].shape)),
        "Top Pages": [item["page_number"] for item in context_items],
        "Top Scores": [round(item["score"], 4) for item in context_items],
        "Answer Style": "Direct factual answer",
        "RAG Answer": answer
    })


# Literary poetry queries
poetry_tests = [
    "Which lines mention death or mortality?",
    "Which lines express loneliness or sadness?",
    "Which lines connect love, democracy, and religion?"
]

for query in poetry_tests:
    answer, context_items = ask_poetry(
        query=query,
        dataset=poetry_dataset,
        n_resources_to_return=3,
        max_new_tokens=256
    )

    comparison_rows.append({
        "Dataset": poetry_dataset["name"],
        "Document Type": "Literary poetry",
        "Chunking Strategy": "Line-based chunking",
        "Query Type": "Thematic / interpretive question",
        "Query": query,
        "Chunk Count": len(poetry_dataset["chunks"]),
        "Embedding Shape": str(tuple(poetry_dataset["embeddings"].shape)),
        "Top Pages": [item["page_number"] for item in context_items],
        "Top Scores": [round(item["score"], 4) for item in context_items],
        "Answer Style": "Interpretive answer based on retrieved excerpts",
        "RAG Answer": answer
    })

comparison_df = pd.DataFrame(comparison_rows)

pd.set_option("display.max_colwidth", 180)
comparison_df

comparison_df.to_csv("nutrition_vs_poetry_rag_comparison.csv", index=False)
print("Comparison table saved.")

pd.set_option("display.max_colwidth", None)
comparison_df

compact_comparison_df = comparison_df[
    [
        "Dataset",
        "Document Type",
        "Chunking Strategy",
        "Query Type",
        "Query",
        "Chunk Count",
        "Top Scores",
        "Answer Style"
    ]
]

compact_comparison_df

import os
import requests

second_pdf_path = "attention_is_all_you_need.pdf"

url = "https://arxiv.org/pdf/1706.03762.pdf"

if not os.path.exists(second_pdf_path):
    response = requests.get(url)
    with open(second_pdf_path, "wb") as f:
        f.write(response.content)
    print("Second PDF downloaded successfully.")
else:
    print("Second PDF already exists.")

import fitz
import re
import pandas as pd
from tqdm.auto import tqdm

def text_formatter(text: str) -> str:
    return text.replace("\n", " ").replace("\xa0", " ").strip()


def open_and_read_pdf_v2(pdf_path: str, page_offset: int = 0) -> list[dict]:
    doc = fitz.open(pdf_path)
    pages_and_texts = []

    for page_number, page in tqdm(enumerate(doc), total=len(doc)):
        text = page.get_text()
        text = text_formatter(text)

        pages_and_texts.append({
            "page_number": page_number + page_offset,
            "page_char_count": len(text),
            "page_word_count": len(text.split(" ")),
            "page_sentence_count_raw": len(text.split(". ")),
            "page_token_count": len(text) / 4,
            "text": text
        })

    doc.close()
    return pages_and_texts


def split_list(input_list: list, slice_size: int) -> list[list[str]]:
    return [input_list[i:i + slice_size] for i in range(0, len(input_list), slice_size)]


def build_rag_dataset_from_pdf(
    pdf_path: str,
    dataset_name: str,
    embedding_model,
    device,
    page_offset: int = 0,
    num_sentence_chunk_size: int = 10,
    min_token_length: int = 30
):
    """
    Turns a PDF into chunks and embeddings for RAG.
    """

    # 1. Read PDF
    pages_and_texts = open_and_read_pdf_v2(
        pdf_path=pdf_path,
        page_offset=page_offset
    )

    # 2. Sentence splitting
    for item in tqdm(pages_and_texts):
        item["sentences"] = list(nlp(item["text"]).sents)
        item["sentences"] = [str(sentence) for sentence in item["sentences"]]
        item["page_sentence_count_spacy"] = len(item["sentences"])

    # 3. Chunking
    for item in tqdm(pages_and_texts):
        item["sentence_chunks"] = split_list(
            input_list=item["sentences"],
            slice_size=num_sentence_chunk_size
        )
        item["num_chunks"] = len(item["sentence_chunks"])

    # 4. Convert chunks to list of dictionaries
    pages_and_chunks_new = []

    for item in tqdm(pages_and_texts):
        for sentence_chunk in item["sentence_chunks"]:
            chunk_dict = {}

            joined_sentence_chunk = "".join(sentence_chunk).replace("  ", " ").strip()
            joined_sentence_chunk = re.sub(r"\.([A-Z])", r". \1", joined_sentence_chunk)

            chunk_dict["page_number"] = item["page_number"]
            chunk_dict["sentence_chunk"] = joined_sentence_chunk
            chunk_dict["chunk_char_count"] = len(joined_sentence_chunk)
            chunk_dict["chunk_word_count"] = len(joined_sentence_chunk.split(" "))
            chunk_dict["chunk_token_count"] = len(joined_sentence_chunk) / 4

            pages_and_chunks_new.append(chunk_dict)

    # 5. Filter short chunks
    df_chunks = pd.DataFrame(pages_and_chunks_new)

    pages_and_chunks_over_min_token_len = df_chunks[
        df_chunks["chunk_token_count"] > min_token_length
    ].to_dict(orient="records")

    # 6. Create embeddings
    text_chunks = [
        item["sentence_chunk"]
        for item in pages_and_chunks_over_min_token_len
    ]

    chunk_embeddings = embedding_model.encode(
        text_chunks,
        batch_size=32,
        convert_to_tensor=True
    ).to(device)

    dataset = {
        "name": dataset_name,
        "pdf_path": pdf_path,
        "chunks": pages_and_chunks_over_min_token_len,
        "embeddings": chunk_embeddings
    }

    print(f"Dataset name: {dataset_name}")
    print(f"Number of chunks: {len(dataset['chunks'])}")
    print(f"Embedding shape: {dataset['embeddings'].shape}")

    return dataset

attention_dataset = build_rag_dataset_from_pdf(
    pdf_path=second_pdf_path,
    dataset_name="Attention Is All You Need PDF",
    embedding_model=embedding_model,
    device=device,
    page_offset=0,
    num_sentence_chunk_size=10,
    min_token_length=30
)

def ask_from_dataset(query, dataset, n_resources_to_return=2, max_new_tokens=256):
    """
    Full RAG pipeline for a selected dataset.
    """

    scores, indices = retrieve_relevant_resources(
        query=query,
        embeddings=dataset["embeddings"],
        n_resources_to_return=n_resources_to_return
    )

    context_items = []

    for score, idx in zip(scores, indices):
        idx = idx.item()
        item = dataset["chunks"][idx].copy()
        item["score"] = score.item()
        context_items.append(item)

    prompt = prompt_formatter(
        query=query,
        context_items=context_items
    )

    model_device = next(llm_model.parameters()).device
    inputs = tokenizer(prompt, return_tensors="pt").to(model_device)

    outputs = llm_model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False,
        pad_token_id=tokenizer.eos_token_id
    )

    generated_tokens = outputs[0][inputs["input_ids"].shape[-1]:]
    answer = tokenizer.decode(generated_tokens, skip_special_tokens=True)

    return answer, context_items

"""compare 2 datasets"""

comparison_tests = [
    {
        "dataset": nutrition_dataset,
        "query": "What are the symptoms of pellagra?"
    },
    {
        "dataset": nutrition_dataset,
        "query": "What are macronutrients, and what roles do they play in the human body?"
    },
    {
        "dataset": attention_dataset,
        "query": "What is self-attention?"
    },
    {
        "dataset": attention_dataset,
        "query": "What is the Transformer architecture?"
    }
]

comparison_results = []

for test in comparison_tests:
    dataset = test["dataset"]
    query = test["query"]

    answer, context_items = ask_from_dataset(
        query=query,
        dataset=dataset,
        n_resources_to_return=2,
        max_new_tokens=256
    )

    comparison_results.append({
        "Dataset": dataset["name"],
        "Query": query,
        "Number of Chunks": len(dataset["chunks"]),
        "Embedding Shape": str(tuple(dataset["embeddings"].shape)),
        "Top Retrieved Pages": [item["page_number"] for item in context_items],
        "Top Scores": [round(item["score"], 4) for item in context_items],
        "RAG Answer": answer
    })

comparison_df = pd.DataFrame(comparison_results)
comparison_df

"""cross-dataset sanity check"""

query = "What are the symptoms of pellagra?"

answer, context_items = ask_from_dataset(
    query=query,
    dataset=attention_dataset,
    n_resources_to_return=2,
    max_new_tokens=256
)

print("Dataset:", attention_dataset["name"])
print("Query:", query)
print("\nAnswer:")
print(answer)

print("\nRetrieved Contexts:")
for item in context_items:
    print(f"Score: {item['score']:.4f}")
    print(f"Page number: {item['page_number']}")
    print_wrapped(item["sentence_chunk"])
    print("-" * 80)





